# Generated by Django 3.1.1 on 2020-09-24 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200924_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='userId',
            new_name='user',
        ),
    ]
