# Generated by Django 3.1.1 on 2020-09-24 19:01

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200924_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='expiration_date',
            field=models.DateTimeField(default=timezone.now()),
            preserve_default=False,
        ),
    ]
